#!/bin/bash

ALTO_URL=$1
SOLR_URL=https://solrlocal:8984/solr/fedora4
OCR_TEXT_FIELD=ocr_text

TEXT=$(xsltproc alto2txt.xsl <(curl -s -k -u "$FCREPO_CREDS" "$ALTO_URL") | sed 's/\\/\\\\/g')

#TODO: need the real ID to add the ocr_text field to
DOC=<<END
{
  "id": "OCR",
  "$OCR_TEXT_FIELD": "$TEXT"
}
END
UPDATE=<<END
{
  "add": {
    "doc": $DOC,
    "boost": 1.0,
    "overwrite": true,
    "commitWithin": 1000
  }
}
END

curl -k -X POST "$SOLR_URL/update" \
  -H 'Content-Type: application/json' \
  --data-binary "$UPDATE"
